services:
  commander:
    image: ghcr.io/jakkoble/hexatask-commander:latest
    container_name: hexatask-commander
    ports:
      - "5271:5271"
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/5271 || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s

  tui:
    image: ghcr.io/jakkoble/hexatask-tui:latest
    depends_on:
      commander:
        condition: service_healthy # <-- warten bis Healthcheck OK
    environment:
      COMMANDER_ADDR: http://commander:5271
      JOB_DIR: /app/jobs
    stdin_open: true
    tty: true
    volumes:
      - ./jobs:/app/jobs
