// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.1
// source: runner.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerServiceClient interface {
	GetJobDetails(ctx context.Context, in *GetJobDetailsRequest, opts ...grpc.CallOption) (*GetJobDetailsResponse, error)
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (RunnerService_StreamLogsClient, error)
}

type runnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerServiceClient(cc grpc.ClientConnInterface) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) GetJobDetails(ctx context.Context, in *GetJobDetailsRequest, opts ...grpc.CallOption) (*GetJobDetailsResponse, error) {
	out := new(GetJobDetailsResponse)
	err := c.cc.Invoke(ctx, "/runner.RunnerService/GetJobDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (RunnerService_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &RunnerService_ServiceDesc.Streams[0], "/runner.RunnerService/StreamLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &runnerServiceStreamLogsClient{stream}
	return x, nil
}

type RunnerService_StreamLogsClient interface {
	Send(*LogMessage) error
	CloseAndRecv() (*StreamLogsResponse, error)
	grpc.ClientStream
}

type runnerServiceStreamLogsClient struct {
	grpc.ClientStream
}

func (x *runnerServiceStreamLogsClient) Send(m *LogMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *runnerServiceStreamLogsClient) CloseAndRecv() (*StreamLogsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RunnerServiceServer is the server API for RunnerService service.
// All implementations must embed UnimplementedRunnerServiceServer
// for forward compatibility
type RunnerServiceServer interface {
	GetJobDetails(context.Context, *GetJobDetailsRequest) (*GetJobDetailsResponse, error)
	StreamLogs(RunnerService_StreamLogsServer) error
	mustEmbedUnimplementedRunnerServiceServer()
}

// UnimplementedRunnerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRunnerServiceServer struct {
}

func (UnimplementedRunnerServiceServer) GetJobDetails(context.Context, *GetJobDetailsRequest) (*GetJobDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobDetails not implemented")
}
func (UnimplementedRunnerServiceServer) StreamLogs(RunnerService_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedRunnerServiceServer) mustEmbedUnimplementedRunnerServiceServer() {}

// UnsafeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServiceServer will
// result in compilation errors.
type UnsafeRunnerServiceServer interface {
	mustEmbedUnimplementedRunnerServiceServer()
}

func RegisterRunnerServiceServer(s grpc.ServiceRegistrar, srv RunnerServiceServer) {
	s.RegisterService(&RunnerService_ServiceDesc, srv)
}

func _RunnerService_GetJobDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).GetJobDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runner.RunnerService/GetJobDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).GetJobDetails(ctx, req.(*GetJobDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunnerServiceServer).StreamLogs(&runnerServiceStreamLogsServer{stream})
}

type RunnerService_StreamLogsServer interface {
	SendAndClose(*StreamLogsResponse) error
	Recv() (*LogMessage, error)
	grpc.ServerStream
}

type runnerServiceStreamLogsServer struct {
	grpc.ServerStream
}

func (x *runnerServiceStreamLogsServer) SendAndClose(m *StreamLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *runnerServiceStreamLogsServer) Recv() (*LogMessage, error) {
	m := new(LogMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RunnerService_ServiceDesc is the grpc.ServiceDesc for RunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runner.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJobDetails",
			Handler:    _RunnerService_GetJobDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _RunnerService_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "runner.proto",
}
